"use client"

interface CountryFlagProps {
  countryCode: string
  countryName?: string
  size?: "sm" | "md" | "lg"
}

const COUNTRY_FLAGS: Record<string, string> = {
  // Major economies
  US: "🇺🇸",
  USA: "🇺🇸",
  "United States": "🇺🇸",
  GB: "🇬🇧",
  UK: "🇬🇧",
  "United Kingdom": "🇬🇧",
  EU: "🇪🇺",
  EUR: "🇪🇺",
  "European Union": "🇪🇺",
  DE: "🇩🇪",
  Germany: "🇩🇪",
  FR: "🇫🇷",
  France: "🇫🇷",
  JP: "🇯🇵",
  Japan: "🇯🇵",
  CN: "🇨🇳",
  China: "🇨🇳",
  CA: "🇨🇦",
  Canada: "🇨🇦",
  AU: "🇦🇺",
  Australia: "🇦🇺",
  CH: "🇨🇭",
  Switzerland: "🇨🇭",
  IT: "🇮🇹",
  Italy: "🇮🇹",
  ES: "🇪🇸",
  Spain: "🇪🇸",
  NL: "🇳🇱",
  Netherlands: "🇳🇱",
  SE: "🇸🇪",
  Sweden: "🇸🇪",
  NO: "🇳🇴",
  Norway: "🇳🇴",
  DK: "🇩🇰",
  Denmark: "🇩🇰",
  FI: "🇫🇮",
  Finland: "🇫🇮",
  BE: "🇧🇪",
  Belgium: "🇧🇪",
  AT: "🇦🇹",
  Austria: "🇦🇹",
  PT: "🇵🇹",
  Portugal: "🇵🇹",
  IE: "🇮🇪",
  Ireland: "🇮🇪",
  GR: "🇬🇷",
  Greece: "🇬🇷",
  PL: "🇵🇱",
  Poland: "🇵🇱",
  CZ: "🇨🇿",
  "Czech Republic": "🇨🇿",
  HU: "🇭🇺",
  Hungary: "🇭🇺",
  SK: "🇸🇰",
  Slovakia: "🇸🇰",
  SI: "🇸🇮",
  Slovenia: "🇸🇮",
  HR: "🇭🇷",
  Croatia: "🇭🇷",
  RO: "🇷🇴",
  Romania: "🇷🇴",
  BG: "🇧🇬",
  Bulgaria: "🇧🇬",
  LT: "🇱🇹",
  Lithuania: "🇱🇹",
  LV: "🇱🇻",
  Latvia: "🇱🇻",
  EE: "🇪🇪",
  Estonia: "🇪🇪",
  MT: "🇲🇹",
  Malta: "🇲🇹",
  CY: "🇨🇾",
  Cyprus: "🇨🇾",
  LU: "🇱🇺",
  Luxembourg: "🇱🇺",
  // Other major economies
  BR: "🇧🇷",
  Brazil: "🇧🇷",
  IN: "🇮🇳",
  India: "🇮🇳",
  RU: "🇷🇺",
  Russia: "🇷🇺",
  KR: "🇰🇷",
  "South Korea": "🇰🇷",
  MX: "🇲🇽",
  Mexico: "🇲🇽",
  ID: "🇮🇩",
  Indonesia: "🇮🇩",
  TR: "🇹🇷",
  Turkey: "🇹🇷",
  SA: "🇸🇦",
  "Saudi Arabia": "🇸🇦",
  ZA: "🇿🇦",
  "South Africa": "🇿🇦",
  AR: "🇦🇷",
  Argentina: "🇦🇷",
  TH: "🇹🇭",
  Thailand: "🇹🇭",
  MY: "🇲🇾",
  Malaysia: "🇲🇾",
  SG: "🇸🇬",
  Singapore: "🇸🇬",
  PH: "🇵🇭",
  Philippines: "🇵🇭",
  VN: "🇻🇳",
  Vietnam: "🇻🇳",
  BD: "🇧🇩",
  Bangladesh: "🇧🇩",
  PK: "🇵🇰",
  Pakistan: "🇵🇰",
  EG: "🇪🇬",
  Egypt: "🇪🇬",
  NG: "🇳🇬",
  Nigeria: "🇳🇬",
  KE: "🇰🇪",
  Kenya: "🇰🇪",
  MA: "🇲🇦",
  Morocco: "🇲🇦",
  DZ: "🇩🇿",
  Algeria: "🇩🇿",
  TN: "🇹🇳",
  Tunisia: "🇹🇳",
  LY: "🇱🇾",
  Libya: "🇱🇾",
  SD: "🇸🇩",
  Sudan: "🇸🇩",
  ET: "🇪🇹",
  Ethiopia: "🇪🇹",
  UG: "🇺🇬",
  Uganda: "🇺🇬",
  TZ: "🇹🇿",
  Tanzania: "🇹🇿",
  GH: "🇬🇭",
  Ghana: "🇬🇭",
  CI: "🇨🇮",
  "Ivory Coast": "🇨🇮",
  SN: "🇸🇳",
  Senegal: "🇸🇳",
  ML: "🇲🇱",
  Mali: "🇲🇱",
  BF: "🇧🇫",
  "Burkina Faso": "🇧🇫",
  NE: "🇳🇪",
  Niger: "🇳🇪",
  TD: "🇹🇩",
  Chad: "🇹🇩",
  CM: "🇨🇲",
  Cameroon: "🇨🇲",
  CF: "🇨🇫",
  "Central African Republic": "🇨🇫",
  GA: "🇬🇦",
  Gabon: "🇬🇦",
  CG: "🇨🇬",
  Congo: "🇨🇬",
  CD: "🇨🇩",
  "Democratic Republic of Congo": "🇨🇩",
  AO: "🇦🇴",
  Angola: "🇦🇴",
  ZM: "🇿🇲",
  Zambia: "🇿🇲",
  ZW: "🇿🇼",
  Zimbabwe: "🇿🇼",
  BW: "🇧🇼",
  Botswana: "🇧🇼",
  NA: "🇳🇦",
  Namibia: "🇳🇦",
  SZ: "🇸🇿",
  Eswatini: "🇸🇿",
  LS: "🇱🇸",
  Lesotho: "🇱🇸",
  MW: "🇲🇼",
  Malawi: "🇲🇼",
  MZ: "🇲🇿",
  Mozambique: "🇲🇿",
  MG: "🇲🇬",
  Madagascar: "🇲🇬",
  MU: "🇲🇺",
  Mauritius: "🇲🇺",
  SC: "🇸🇨",
  Seychelles: "🇸🇨",
  KM: "🇰🇲",
  Comoros: "🇰🇲",
  DJ: "🇩🇯",
  Djibouti: "🇩🇯",
  SO: "🇸🇴",
  Somalia: "🇸🇴",
  ER: "🇪🇷",
  Eritrea: "🇪🇷",
  SS: "🇸🇸",
  "South Sudan": "🇸🇸",
  // Middle East
  AE: "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  QA: "🇶🇦",
  Qatar: "🇶🇦",
  KW: "🇰🇼",
  Kuwait: "🇰🇼",
  BH: "🇧🇭",
  Bahrain: "🇧🇭",
  OM: "🇴🇲",
  Oman: "🇴🇲",
  YE: "🇾🇪",
  Yemen: "🇾🇪",
  JO: "🇯🇴",
  Jordan: "🇯🇴",
  LB: "🇱🇧",
  Lebanon: "🇱🇧",
  SY: "🇸🇾",
  Syria: "🇸🇾",
  IQ: "🇮🇶",
  Iraq: "🇮🇶",
  IR: "🇮🇷",
  Iran: "🇮🇷",
  AF: "🇦🇫",
  Afghanistan: "🇦🇫",
  // Asia Pacific
  NZ: "🇳🇿",
  "New Zealand": "🇳🇿",
  FJ: "🇫🇯",
  Fiji: "🇫🇯",
  PG: "🇵🇬",
  "Papua New Guinea": "🇵🇬",
  SB: "🇸🇧",
  "Solomon Islands": "🇸🇧",
  VU: "🇻🇺",
  Vanuatu: "🇻🇺",
  NC: "🇳🇨",
  "New Caledonia": "🇳🇨",
  PF: "🇵🇫",
  "French Polynesia": "🇵🇫",
  WS: "🇼🇸",
  Samoa: "🇼🇸",
  TO: "🇹🇴",
  Tonga: "🇹🇴",
  TV: "🇹🇻",
  Tuvalu: "🇹🇻",
  KI: "🇰🇮",
  Kiribati: "🇰🇮",
  NR: "🇳🇷",
  Nauru: "🇳🇷",
  PW: "🇵🇼",
  Palau: "🇵🇼",
  FM: "🇫🇲",
  Micronesia: "🇫🇲",
  MH: "🇲🇭",
  "Marshall Islands": "🇲🇭",
  // Americas
  CL: "🇨🇱",
  Chile: "🇨🇱",
  PE: "🇵🇪",
  Peru: "🇵🇪",
  CO: "🇨🇴",
  Colombia: "🇨🇴",
  VE: "🇻🇪",
  Venezuela: "🇻🇪",
  EC: "🇪🇨",
  Ecuador: "🇪🇨",
  BO: "🇧🇴",
  Bolivia: "🇧🇴",
  PY: "🇵🇾",
  Paraguay: "🇵🇾",
  UY: "🇺🇾",
  Uruguay: "🇺🇾",
  GY: "🇬🇾",
  Guyana: "🇬🇾",
  SR: "🇸🇷",
  Suriname: "🇸🇷",
  GF: "🇬🇫",
  "French Guiana": "🇬🇫",
  // Central America & Caribbean
  GT: "🇬🇹",
  Guatemala: "🇬🇹",
  BZ: "🇧🇿",
  Belize: "🇧🇿",
  SV: "🇸🇻",
  "El Salvador": "🇸🇻",
  HN: "🇭🇳",
  Honduras: "🇭🇳",
  NI: "🇳🇮",
  Nicaragua: "🇳🇮",
  CR: "🇨🇷",
  "Costa Rica": "🇨🇷",
  PA: "🇵🇦",
  Panama: "🇵🇦",
  CU: "🇨🇺",
  Cuba: "🇨🇺",
  JM: "🇯🇲",
  Jamaica: "🇯🇲",
  HT: "🇭🇹",
  Haiti: "🇭🇹",
  DO: "🇩🇴",
  "Dominican Republic": "🇩🇴",
  PR: "🇵🇷",
  "Puerto Rico": "🇵🇷",
  TT: "🇹🇹",
  "Trinidad and Tobago": "🇹🇹",
  BB: "🇧🇧",
  Barbados: "🇧🇧",
  GD: "🇬🇩",
  Grenada: "🇬🇩",
  VC: "🇻🇨",
  "Saint Vincent and the Grenadines": "🇻🇨",
  LC: "🇱🇨",
  "Saint Lucia": "🇱🇨",
  DM: "🇩🇲",
  Dominica: "🇩🇲",
  AG: "🇦🇬",
  "Antigua and Barbuda": "🇦🇬",
  KN: "🇰🇳",
  "Saint Kitts and Nevis": "🇰🇳",
  BS: "🇧🇸",
  Bahamas: "🇧🇸",
}

export function CountryFlag({ countryCode, countryName, size = "md" }: CountryFlagProps) {
  const flag = COUNTRY_FLAGS[countryCode] || COUNTRY_FLAGS[countryName || ""] || "🌍"

  const sizeClasses = {
    sm: "text-sm",
    md: "text-base",
    lg: "text-lg",
  }

  return (
    <span className={`${sizeClasses[size]} leading-none`} title={countryName || countryCode}>
      {flag}
    </span>
  )
}
